### ISSUE TITLE
Convert links

### ISSUE THREAD

**Issue by juanpastas** [jlord/sheetdown#18]
Is this a possibility?

**Comment by jlord** [comment]
Just to clarify, do you mean convert HTML links from a spreadsheet into markdown links? Yeah, that's possible for sure and a good idea :sparkles:

**Comment by juanpastas** [comment]
Yes, that's what I meant.

**Comment by jlord** [comment]
Cool :+1: yeah, having that would be good.

**Comment by jlord** [comment]
I started working on this and realized that if there is just a like in a cell in a spreadsheet, it can't really be converted to markdown because what would the link text be? i.e. [what goes here](link)

We can turn html links, like `<a href="http://site.com">Link</a>` though so I'll add that, but people will have to be using html within their spreadsheet.
